name: artifact demo
on:
    workflow_dispatch:

jobs:
    demo:
        runs-on: ubuntu-latest

        steps:
            - name: Create Report and file
              run: |
                mkdir reports
                echo "Name: Srinivas" > reports/student1.txt
                echo "Age: 21" >> reports/student1.txt
                echo "City: Pune" >> reports/student1.txt

            - name: Upload Report
              uses: actions/upload-artifact@v4

              with:
                name: Student1_report
                path: reports/