name: artifact demo
on:
    workflow_dispatch:

jobs:
    demo:
        runs-on: ubuntu-latest

        steps:
            - name: Create Report
              run: |
               echo "GitHub Actions Report" > report.txt

            - name: Upload Report
              uses: actions/upload-artifact@v4

              with:
                name: MyReport
                path: report.txt