name: if Demo
on:
    workflow_dispatch:

jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Always run"

            # - name: Main Branch only
            #   
            #   run: |
            #     echo "This runs only on main"
            - name: Development
              if: ${{github.ref_name == 'dev' && runner.os == 'Linux'}}
              run: |
                echo "Development Build"

            - name: Testing
              if: ${{success()}}
              run: |
                echo "Testing....."