name: job output demo
on:
    workflow_dispatch:
jobs:
    
    naam:
       runs-on: ubuntu-latest

       outputs:
         student_name: ${{steps.student.outputs.NAME}}

       steps:
         - name: Student Name
           id: student
           run: |
             echo "NAME=Srini" >> $GITHUB_OUTPUT

    report:
       needs: naam
       runs-on: ubuntu-latest

       steps:
          - name: Report get
            run: |
                echo "Hello ${{needs.naam.outputs.student_name}}"

    bye:
        needs: naam
        runs-on: ubuntu-latest

        steps:
            - name: Bye him
              run: |
                echo "Bye ${{needs.naam.outputs.student_name}}"

     