name: multiple jobs

on:
    push:

jobs:

    job1:
        runs-on: ubuntu-latest

        steps:
            - run: echo this is Job1

    job2:
        runs-on: ubuntu-latest

        steps:
            - run : echo this is job2
