name: outputs Demo
on:
    workflow_dispatch:

jobs:
    demo:
        runs-on: ubuntu-latest

        steps:
            - name: Generate Version
              id: student
              run: |
                echo "Name=Srini" >> $GITHUB_OUTPUT
                echo "Age=20" >> $GITHUB_OUTPUT
                echo "City=Pune" >> $GITHUB_OUTPUT

            - name: Print Student
              run: |
                echo "Name = ${{steps.student.outputs.Name}}"