name : Learning GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  demo:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Python Version
        run: python --version
      
      - name: List Files
        run: ls -la