name : Learning GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  demo:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List files
        run: ls -la